Implement utime/utimes/futimens
vitasdk/newlib pull request #87
Opened 2022-05-29 04:00 UTC by SonicMastr

2022-05-29 19:46 UTC, isage commented
Fix tabs/spaces mix, please.

2022-05-29 20:47 UTC, SonicMastr commented
Oh ffs. Yeah. Sorry.

2022-06-01 02:22 UTC, d3m3vilurr requested changes

2022-06-01 02:22 UTC, d3m3vilurr commented on newlib/libc/sys/vita/sys/utime.h
> +#ifndef _SYS_UTIME_H
please add license holder of this header

2022-06-01 02:22 UTC, d3m3vilurr commented on newlib/libc/sys/vita/utime.c
> +#define TRY(x) {rid=x; if (rid < 0) {errno = __vita_sce_errno_to_errno(rid, ERROR_GENERIC); return -1;}}
`TRY` action needs `free(full_path);` in `utimes`.
so maybe better it define in `utimes` and `undef` after function body.
(or just use `goto` to exit the function in error case :))

and also can you make it to `do { ... } while (0);` form?

2022-06-01 06:51 UTC, merged