WIP: use sceClib memory functions
vitasdk/newlib pull request #89
Opened 2022-07-23 19:08 UTC by frangarcj

2022-08-22 18:21 UTC, isage commented on newlib/libc/machine/arm/memcpy-stub.c
> +void memcpy (void *dest, const void *source, size_t n){
`void *`

2022-08-22 18:21 UTC, isage commented on newlib/libc/machine/arm/memmove.c
> +void memmove (void *dest, const void *source, size_t n){
`void *`

2022-08-22 18:21 UTC, isage commented on newlib/libc/machine/arm/memset.c
> +void memset (void *dest, int c, size_t n){
`void *`

2022-08-24 11:42 UTC, d3m3vilurr requested changes
indentations have to be hardtab :)

2022-08-25 01:06 UTC, merged